### ISSUE TITLE
bash brace expansion broken in `npm run lint`

### ISSUE THREAD

**Issue by pabo** [jonidelv/generator-create-redux-app#3]
`package.json` contains the lines
```
  "scripts": {
   ...
    "lint": "eslint 'src/**/*.{js}'",
```
 but the bash brace expansion doesn't work with only one value. I suggest changing it to 
``` "lint": "eslint 'src/**/*.{js,jsx}'",```
or 
``` "lint": "eslint 'src/**/*.js'",```

**Comment by jonidelv** [comment]
I updated the starter is using [prettier](https://prettier.io/) now so the `package.json` doesn't contain that any more.  If you want to have this feature with out upgrading the starter.
install `eslint-config-prettier`, `lint-staged` and `prettier`. And copy this options [package.json](https://github.com/jonidelv/generator-create-redux-app/blob/master/example/package.json)
