### ISSUE TITLE
Absolute Paths don't get resolved

### ISSUE THREAD

**Issue by zetixar** [jonidelv/generator-create-redux-app#4]
Absolute Paths don't get resolved right off the bat. `npm install` works fine but when I do `npm start` it can't resolve 'store' module path or any other absolute paths. 

Maybe there is something wrong with my dev environment, idk.
<img width="887" alt="screen shot 2017-09-19 at 9 18 44 am" src="https://user-images.githubusercontent.com/16512934/30594990-e2831a04-9d1d-11e7-9c1c-f35aabcd5c62.png">

**Comment by jonidelv** [comment]
I just tried and is working fine for me, make sure you have this file in the root folder
`.env` with this content
```
NODE_PATH=src/
```
it will make your path absolute to the `src` folder.

**Comment by zetixar** [comment]
I do have the `.env` file that automatically gets generated by `yo create-redux-app`, in the root folder with`NODE_PATH=src/` in it, but still it can't help resolving the absolute paths for me. 
The only way that I could get it work was to add `NODE_PATH=./src` to the npm scripts like this: `"start": "NODE_PATH=./src react-scripts start"`.
It seems that the real issue is related to 'create-react-app' itself, e.g. https://github.com/facebookincubator/create-react-app/issues/2230

**Comment by jonidelv** [comment]
Glad you made it work, yeah I think is related to `create-react-app`.

**Comment by zetixar** [comment]
Since this is not an issue with _generator-create-redux-app_ itself and there is also a semi hacky solution for this -at least for now- I close this.
